### PR TITLE
Add missing handler registration

### PR DESCRIPTION
**Pull request by daliwei**
cc @pierre @sbrossie

### CODE REVIEW

**Comment by sbrossie** [comment]
👍

**Comment by daliwei** [comment]
@sbrossie @pierre Thanks for review. Can you pls release a new version?

**Comment by pierre** [comment]
> @sbrossie @pierre Thanks for review. Can you pls release a new version?

You can actually trigger one by preparing a PR against the `release` branch (just make sure it is up-to-date with `master` and update the `NEWS` file).

**Comment by daliwei** [comment]
Oh. I forgot that. Thanks for reminding.

**Pull request merged**
