### PR TITLE
With new adyen checkout

### PR DESCRIPTION
**Pull request by reshmabidikar**
Includes the following changes (Refer to the commit history):

- Replaced Kill Bill code with Wovenware code (3814d62023c82d7d670ad848e8df4b8945fedce0)
- Fixed `pom.xml` for the code to build (ada583867c27296b86b886f9829786c179339e70)
- Deleted circleci configuration file and added Github actions ci workflow (792c451c05305bfbbd5fb8b1f3d05eddfefba12d)
- Update to pom for code to build during ci (a1075a329d8eb067db3e348e9396d595b78a507a and b20d148713bb1d09f81031a056a250ad0f59a0ae)
- Added `codeql` workflow (ade2b0ecea865c89dccb17b02624ac9ec53c641e)
- Updated version in `pom.xml` (64d084b5357a151bdcd75e945e81d34b0e7485e2)
- Cleaned up Readme (fdc9299838eef85a41ed677659a07c9f094286f2 and c5b292a61bfaafb5fc4204bd8f4a44614227c869)

A couple of questions:
1. Looks like the circleci build is somehow still referenced: https://app.circleci.com/pipelines/github/killbill/killbill-adyen-plugin/38. This needs to be deleted I guess.
2. The `pom.xml` uses the jacoco plugin (See [this](https://github.com/killbill/killbill-adyen-plugin/blob/7744487d5f00e45000d700fc9981cc6c258d25a4/pom.xml#L440)). Other Kill Bill plugins normally do not use this plugin, so perhaps we can remove this? Anyway, the build fails due to this plugin so I had to disable the check [here ](https://github.com/killbill/killbill-adyen-plugin/blob/7744487d5f00e45000d700fc9981cc6c258d25a4/pom.xml#L33). Or should we leave this as it is in `0.22.x` and remove it when we port to `0.24.x`?
3. In the `pom.xml`, I specified the version as `0.8.1-SNAPSHOT` [here](https://github.com/killbill/killbill-adyen-plugin/blob/7744487d5f00e45000d700fc9981cc6c258d25a4/pom.xml#L21) since the [previous version](https://github.com/killbill/killbill-adyen-plugin/blob/5bb6ad36a868bab15a4123af32a8c453f383e3b7/pom.xml#L27) was  `0.8.0-SNAPSHOT`. Does this look right or should we move to `0.9.0`?

### CODE REVIEW

**Comment by pierre** [comment]
> 1. Looks like the circleci build is somehow still referenced: https://app.circleci.com/pipelines/github/killbill/killbill-adyen-plugin/38. This needs to be deleted I guess.

Yes, there was still a webhook in place. I've just removed it.

> 2. The `pom.xml` uses the jacoco plugin (See [this](https://github.com/killbill/killbill-adyen-plugin/blob/7744487d5f00e45000d700fc9981cc6c258d25a4/pom.xml#L440)). Other Kill Bill plugins normally do not use this plugin, so perhaps we can remove this? Anyway, the build fails due to this plugin so I had to disable the check [here ](https://github.com/killbill/killbill-adyen-plugin/blob/7744487d5f00e45000d700fc9981cc6c258d25a4/pom.xml#L33). Or should we leave this as it is in `0.22.x` and remove it when we port to `0.24.x`?

Agreed - you can remove it.

> 3. In the `pom.xml`, I specified the version as `0.8.1-SNAPSHOT` [here](https://github.com/killbill/killbill-adyen-plugin/blob/7744487d5f00e45000d700fc9981cc6c258d25a4/pom.xml#L21) since the [previous version](https://github.com/killbill/killbill-adyen-plugin/blob/5bb6ad36a868bab15a4123af32a8c453f383e3b7/pom.xml#L27) was  `0.8.0-SNAPSHOT`. Does this look right or should we move to `0.9.0`?

Best to move to 0.9.0 to make it clear it's a large update. 👍

**Review by sbrossie — COMMENTED** [review]
Looks good. It's a lot of code change - as expected - should we merge to a temporary branch first, e.g `new-adyen-staging` so we can open a clean PR with the next upcoming item, and then merge everything in master when work as been completed? @pierre Thoughts?

**Comment by pierre** [comment]
> Looks good. It's a lot of code change - as expected - should we merge to a temporary branch first, e.g `new-adyen-staging` so we can open a clean PR with the next upcoming item, and then merge everything in master when work as been completed? @pierre Thoughts?

Sounds good!

**Comment by meden** [comment]
Hello, as an user of this plugin (v. 0.8.0, custom build), I'm wondering: is this a drop-in replacement for the previous version?

As fas as I can see:
1. It does not support multiple merchants at once.
2. It has a different DB schema, but it does not provide migrations.

There is any upgrade path to follow?

Thank you

**Comment by reshmabidikar** [comment]
> Hello, as an user of this plugin (v. 0.8.0, custom build), I'm wondering: is this a drop-in replacement for the previous version?

Yes, that is correct.
> 
> As fas as I can see:
> 
> 1. It does not support multiple merchants at once.
> 2. It has a different DB schema, but it does not provide migrations.
> 
> There is any upgrade path to follow?
> 
> Thank you

This PR is still a work in progress. If you would like a stable version of the Adyen plugin that supports dropin, please use https://github.com/Wovenware/killbill-adyen-plugin

If you have any other queries, please feel free to reach out via the [mailing list](https://groups.google.com/g/killbilling-users).

**Comment by reshmabidikar** [comment]
> > Looks good. It's a lot of code change - as expected - should we merge to a temporary branch first, e.g `new-adyen-staging` so we can open a clean PR with the next upcoming item, and then merge everything in master when work as been completed? @pierre Thoughts?
> 
> Sounds good!

Done, created the `new-adyen-staging` branch and modified PR to use it.

**Review by sbrossie — APPROVED** [review]

**Pull request merged**
